# Comparación de datasets — Docentes 2025 vs 2026

Corre las funciones de `compare_datasets_generic.py` sobre los datasets de **docentes**:

- `reporte_comparacion` / `compare_datasets` → diferencias de columnas, categorías y cantidades entre 2025 y 2026.
- `reporte_duplicados` / `detectar_duplicados` → filas repetidas en cada año.

Por defecto usa los **CSV limpios** generados por `estructura.py`. Para comparar los `.xlsx` crudos, cambiá `USAR_LIMPIOS = False` en la celda de config.

In [20]:
from pathlib import Path

import pandas as pd

# Todas las funciones vienen centralizadas del modulo compare_datasets_generic.py
from compare_datasets_generic import (
    cargar,                 # lee csv/xlsx segun extension
    preparar_para_comparar, # unifica dtypes para poder comparar
    compare_datasets,       # reporte estructurado (dict)
    reporte_comparacion,    # reporte en texto
    detectar_desfasajes,    # deteccion operable (con_filas=True -> agrega n_filas)
    detectar_duplicados,    # mascara de duplicados
    reporte_duplicados,     # reporte de duplicados en texto
    limpiar_duplicados_df,  # limpieza -> DataFrame nuevo sin duplicados
)

In [21]:
# ---- Config ----
USAR_LIMPIOS = True  # True: CSV limpios de processed/ ; False: .xlsx crudos

# Carpeta fija: solo los datos de 2025-2025.
CARPETA_DATOS = Path.home() / "Downloads" / "Datos Ceibal 2025-2025"
assert CARPETA_DATOS.exists(), f"No existe la carpeta de datos: {CARPETA_DATOS}"

if USAR_LIMPIOS:
    RUTA_2025 = CARPETA_DATOS / "processed" / "docentes_2025_clean.csv"
    RUTA_2026 = CARPETA_DATOS / "processed" / "docentes_2026_clean.csv"
else:
    RUTA_2025 = CARPETA_DATOS / "datosUCU2025_doc.xlsx"
    RUTA_2026 = CARPETA_DATOS / "datosUCU2026_doc.xlsx"

print("Carpeta:", CARPETA_DATOS)
print("2025   :", RUTA_2025.name)
print("2026   :", RUTA_2026.name)

Carpeta: /Users/gustavohunter/Downloads/Datos Ceibal 2025-2025
2025   : docentes_2025_clean.csv
2026   : docentes_2026_clean.csv

In [22]:
doc25 = cargar(RUTA_2025)
doc26 = cargar(RUTA_2026)

print(f"docentes 2025: {doc25.shape[0]:,} filas x {doc25.shape[1]} cols")
print(f"docentes 2026: {doc26.shape[0]:,} filas x {doc26.shape[1]} cols")
doc25.head()

docentes 2025: 148,372 filas x 25 cols
docentes 2026: 155,745 filas x 25 cols

,ID_persona,ID_CENTRO_docentes,Dias6,Dias5,Dias4,Sexo,ZONA,tipo_centro,Rubro,dept_nombre,...,IVSMEDIA,ANIOLECTIVO,ivsmedia_q,contexto_q,contexto_zona,vuln_q,dias_totales,accedio,tipo,anio
0,ID_00001,CENTRO_0001,14,14,12,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,40,1,docentes,2025
1,ID_00001,CENTRO_0002,14,14,12,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,40,1,docentes,2025
2,ID_00002,CENTRO_0003,1,0,0,M,Urbana,Liceo Público,DGES,CANELONES,...,NaN,2025,NaN,NaN,NaN,NaN,1,1,docentes,2025
3,ID_00003,CENTRO_0004,2,6,11,F,Urbana,Liceo Público,DGES,SORIANO,...,NaN,2025,NaN,NaN,NaN,NaN,19,1,docentes,2025
4,ID_00003,CENTRO_0004,2,6,11,F,Urbana,Liceo Público,DGES,SORIANO,...,NaN,2025,NaN,NaN,NaN,NaN,19,1,docentes,2025

### Preparación para comparar

`compare_datasets` agrupa y hace un `merge` interno sobre las columnas de texto. Dos situaciones de estos datos lo rompen y `preparar_para_comparar` (del módulo) las resuelve antes:

1. **Columnas vacías en un solo año** — p. ej. `IVSMEDIA` está 100% vacía en 2025 (docentes) y `contexto_zona` está vacía en 2026. Una columna toda-NaN se lee como `float64` y no aporta comparación de valores → **se excluyen**.
2. **Columnas numéricas en un año y texto en el otro** (con datos en ambos) → se pasan a **texto** en los dos para poder compararlas como categorías.

In [23]:
doc25c, doc26c = preparar_para_comparar(doc25, doc26)

Columnas vacias en un dataset (excluidas): ['IVSMEDIA', 'ivsmedia_q', 'contexto_zona']
Columnas mixto (num/texto) pasadas a texto: (ninguna)

## 1. Reporte de comparación (texto legible)

`reporte_comparacion` corre internamente `compare_datasets` y arma un texto listo para leer.

In [24]:

print(reporte_comparacion(doc25c, doc26c, name1="2025", name2="2026"))

COMPARACIÓN: 2025  vs  2026
============================================================
Filas totales -> 2025: 148372 | 2026: 155745
Columnas categóricas comparadas: ['ID_persona', 'ID_CENTRO_docentes', 'Sexo', 'ZONA', 'tipo_centro', 'Rubro', 'dept_nombre', 'ciclo', 'grado', 'grupo', 'MATERIA', 'CONTEXTO', 'tipo']
Columnas numéricas comparadas:   ['Dias6', 'Dias5', 'Dias4', 'ANIOLECTIVO', 'contexto_q', 'vuln_q', 'dias_totales', 'accedio', 'anio']

1) COLUMNAS QUE NO COINCIDEN
------------------------------------------------------------
Solo en 2025:
  (ninguna)
Solo en 2026:
  (ninguna)

2) CATEGORÍAS QUE NO COINCIDEN
------------------------------------------------------------
Columna 'ID_persona':
  Solo en 2025:
    - id_00001
    - id_00002
    - id_00005
    - id_00008
    - id_00010
    - id_00014
    - id_00019
    - id_00020
    - id_00021
    - id_00023
    - id_00031
    - id_00032
    - id_00034
    - id_00039
    - id_00047
    - id_00064
    - id_00066
    - id_00069
    - id_00075
    - id_00090
    ... y 5317 más
  Solo en 2026:
    - id_36779
    - id_36780
    - id_36781
    - id_36782
    - id_36783
    - id_36784
    - id_36785
    - id_36786
    - id_36787
    - id_36788
    - id_36789
    - id_36790
    - id_36791
    - id_36792
    - id_36793
    - id_36794
    - id_36795
    - id_36796
    - id_36797
    - id_36798
    ... y 6896 más
Columna 'ID_CENTRO_docentes':
  Solo en 2025:
    - centro_0233
    - centro_0366
    - centro_0412
    - centro_0588
    - centro_0884
    - centro_0927
    - centro_0936
    - centro_1053
    - centro_1074
    - centro_1121
    - centro_1251
    - centro_1293
    - centro_1294
    - centro_1350
    - centro_1375
    - centro_1383
    - centro_1415
    - centro_1419
    - centro_1443
    - centro_1449
    ... y 35 más
  Solo en 2026:
    - centro_2509
    - centro_2510
    - centro_2511
    - centro_2512
    - centro_2513
    - centro_2514
    - centro_2515
    - centro_2516
    - centro_2517
    - centro_2518
    - centro_2519
    - centro_2520
    - centro_2521
    - centro_2522
    - centro_2523
    - centro_2524
    - centro_2525
    - centro_2526
    - centro_2527
    - centro_2528
    ... y 116 más
Columna 'ciclo':
  Solo en 2025:
    - articulacion educacion media basica
    - bachillerato profesional
  Solo en 2026:
    - ctt especializacion
    - educacion media basica tecnologica
Columna 'grado':
  Solo en 2025:
    (ninguna)
  Solo en 2026:
    - no aplica
Columna 'grupo':
  Solo en 2025:
    - 1o.ems g.18
    - 1o.ems g.19
    - 2do.csh g. 5 nc-ha
    - 2do.csh g.14
    - 2do.csh g.15
    - 2do.csh g.16
    - 2do.ct g. 5
    - 2do.ct g. 6
    - 2do.ct g. 7
    - 2do.ct g. 8
    - 2do.ct g. 9
    - 2do.ct g.10
    - 2do.ct g.11
    - 2do.ct g.12
    - 2do.ct g.13
    - 2do.ct g.14
    - 2do.ct g.15
    - 3ro.cshd g. 1
    - 3ro.cshd g. 2
    - 3ro.cshd g. 3
    ... y 89 más
  Solo en 2026:
    - 1b||0
    - 1c||0
    - 1d||0
    - 1e||0
    - 1f||0
    - 1ro. g. 1_anual_s1
    - 2do.csh g. 6 nc-ha
    - 2do.cv g. 1
    - 2do.cv g. 2
    - 2do.cv g. 3
    - 2do.cv g. 4
    - 2do.cv g. 5
    - 2do.cv g. 6
    - 2do.cv g. 7
    - 2do.cv g. 8
    - 3ro.c.art. g. 4
    - 3ro.cad g. 1
    - 3ro.ct g. 1
    - 3ro.ct g. 2
    - 3ro.ct g. 3
    ... y 82 más
Columna 'MATERIA':
  Solo en 2025:
    - adm. y gestion de obras iii
    - administ.y emprendedurismo
    - administracion organizacion taller
    - administracion y costos
    - artes escenicas
    - c.del espacio y tec.aplic.(op)
    - c.experimentales introduccion
    - ciencias exp. biologia
    - ciencias exp. introduccion
    - comp form info
    - comp. form. c. lab. c. ciudadania
    - comp. form. ciudadania
    - comp. form.c. lab. t. y produccion
    - componente c. sociales y arte
    - componente ciencias exp.
    - componente ciencias exp. biologia
    - componente ciencias exp. quimica
    - componente ciencias fis. mat. fis.
    - componente ciencias fis. mat. fisic
    - componente fis.mat. matematica
    ... y 106 más
  Solo en 2026:
    - actividad fisica y salud
    - alfabetizacion laboral
    - analisis contable y financiero
    - astronomia
    - automatizacion
    - back end ii
    - biodiversidad y cuidado de ambiente
    - biologia marina
    - botanica
    - c.comput.y tec.digitales (op.)
    - ciencia fisico quimica
    - comp. y prod. musical: ensamble ii
    - computacion aplicada
    - comunicacion corporativa
    - control de calidad en logistica
    - convertidores avanzados
    - cs.fisico-quimicas
    - danza (op.)
    - diseno de artes de pesca
    - documentacion del proy. contructiv
    ... y 165 más

RESUMEN
------------------------------------------------------------
  Combinaciones comunes comparadas: 25907
  Combinaciones con cantidad desfasada: 160817
  Columnas con categorías desfasadas: ['ID_persona', 'ID_CENTRO_docentes', 'ciclo', 'grado', 'grupo', 'MATERIA']

## 2. Resultado estructurado (dict con DataFrames)

`compare_datasets` devuelve el detalle completo para inspeccionar a mano.

In [25]:
resultado = compare_datasets(doc25c, doc26c, name1="2025", name2="2026")
resultado["resumen"]

{'columnas_solo_en_2025': [],
 'columnas_solo_en_2026': [],
 'columnas_categoricas_comparadas': ['ID_persona',
  'ID_CENTRO_docentes',
  'Sexo',
  'ZONA',
  'tipo_centro',
  'Rubro',
  'dept_nombre',
  'ciclo',
  'grado',
  'grupo',
  'MATERIA',
  'CONTEXTO',
  'tipo'],
 'columnas_numericas_comparadas': ['Dias6',
  'Dias5',
  'Dias4',
  'ANIOLECTIVO',
  'contexto_q',
  'vuln_q',
  'dias_totales',
  'accedio',
  'anio'],
 'columnas_con_categorias_desfasadas': ['ID_persona',
  'ID_CENTRO_docentes',
  'ciclo',
  'grado',
  'grupo',
  'MATERIA'],
 'combinaciones_comunes_comparadas': 25907,
 'combinaciones_con_cantidad_desfasada': 160817,
 'filas_totales_2025': 148372,
 'filas_totales_2026': 155745}

In [26]:
# Categorias (valores de texto) que aparecen en un solo anio
resultado["categorias_desfasadas"]

{'ID_persona': {'solo_en_2025': ['id_00001',
   'id_00002',
   'id_00005',
   'id_00008',
   'id_00010',
   'id_00014',
   'id_00019',
   'id_00020',
   'id_00021',
   'id_00023',
   'id_00031',
   'id_00032',
   'id_00034',
   'id_00039',
   'id_00047',
   'id_00064',
   'id_00066',
   'id_00069',
   'id_00075',
   'id_00090',
   'id_00093',
   'id_00100',
   'id_00117',
   'id_00119',
   'id_00122',
   'id_00125',
   'id_00127',
   'id_00132',
   'id_00135',
   'id_00139',
   'id_00142',
   'id_00156',
   'id_00164',
   'id_00167',
   'id_00183',
   'id_00195',
   'id_00202',
   'id_00206',
   'id_00211',
   'id_00213',
   'id_00214',
   'id_00218',
   'id_00231',
   'id_00234',
   'id_00236',
   'id_00244',
   'id_00252',
   'id_00256',
   'id_00266',
   'id_00295',
   'id_00304',
   'id_00315',
   'id_00319',
   'id_00325',
   'id_00326',
   'id_00334',
   'id_00335',
   'id_00337',
   'id_00338',
   'id_00345',
   'id_00350',
   'id_00352',
   'id_00357',
   'id_00371',
   'id_00384',
   'id_00387',
   'id_00394',
   'id_00397',
   'id_00404',
   'id_00407',
   'id_00411',
   'id_00425',
   'id_00433',
   'id_00437',
   'id_00443',
   'id_00445',
   'id_00447',
   'id_00449',
   'id_00454',
   'id_00461',
   'id_00462',
   'id_00465',
   'id_00469',
   'id_00472',
   'id_00478',
   'id_00481',
   'id_00491',
   'id_00493',
   'id_00499',
   'id_00501',
   'id_00526',
   'id_00529',
   'id_00541',
   'id_00543',
   'id_00548',
   'id_00550',
   'id_00552',
   'id_00558',
   'id_00567',
   'id_00572',
   'id_00573',
   'id_00574',
   'id_00584',
   'id_00587',
   'id_00592',
   'id_00593',
   'id_00594',
   'id_00625',
   'id_00628',
   'id_00638',
   'id_00649',
   'id_00652',
   'id_00655',
   'id_00661',
   'id_00664',
   'id_00668',
   'id_00670',
   'id_00671',
   'id_00673',
   'id_00681',
   'id_00687',
   'id_00698',
   'id_00700',
   'id_00716',
   'id_00730',
   'id_00736',
   'id_00743',
   'id_00747',
   'id_00750',
   'id_00760',
   'id_00773',
   'id_00775',
   'id_00780',
   'id_00794',
   'id_00800',
   'id_00803',
   'id_00808',
   'id_00836',
   'id_00841',
   'id_00847',
   'id_00851',
   'id_00865',
   'id_00866',
   'id_00868',
   'id_00869',
   'id_00870',
   'id_00872',
   'id_00879',
   'id_00884',
   'id_00886',
   'id_00903',
   'id_00904',
   'id_00905',
   'id_00907',
   'id_00908',
   'id_00909',
   'id_00915',
   'id_00923',
   'id_00928',
   'id_00932',
   'id_00936',
   'id_00953',
   'id_00955',
   'id_00958',
   'id_00961',
   'id_00979',
   'id_00980',
   'id_00983',
   'id_00984',
   'id_00990',
   'id_00999',
   'id_01007',
   'id_01008',
   'id_01019',
   'id_01025',
   'id_01040',
   'id_01043',
   'id_01044',
   'id_01048',
   'id_01049',
   'id_01054',
   'id_01061',
   'id_01064',
   'id_01068',
   'id_01071',
   'id_01079',
   'id_01087',
   'id_01090',
   'id_01092',
   'id_01096',
   'id_01111',
   'id_01115',
   'id_01124',
   'id_01153',
   'id_01171',
   'id_01173',
   'id_01176',
   'id_01179',
   'id_01194',
   'id_01197',
   'id_01199',
   'id_01201',
   'id_01208',
   'id_01210',
   'id_01215',
   'id_01216',
   'id_01217',
   'id_01221',
   'id_01232',
   'id_01235',
   'id_01241',
   'id_01273',
   'id_01281',
   'id_01308',
   'id_01312',
   'id_01318',
   'id_01325',
   'id_01326',
   'id_01331',
   'id_01341',
   'id_01343',
   'id_01379',
   'id_01380',
   'id_01387',
   'id_01390',
   'id_01409',
   'id_01418',
   'id_01436',
   'id_01443',
   'id_01457',
   'id_01466',
   'id_01471',
   'id_01484',
   'id_01490',
   'id_01498',
   'id_01504',
   'id_01516',
   'id_01517',
   'id_01535',
   'id_01560',
   'id_01564',
   'id_01566',
   'id_01575',
   'id_01585',
   'id_01595',
   'id_01598',
   'id_01599',
   'id_01612',
   'id_01632',
   'id_01642',
   'id_01645',
   'id_01650',
   'id_01662',
   'id_01663',
   'id_01667',
   'id_01669',
   'id_01672',
   'id_01676',
   'id_01677',
   'id_01684',
   'id_01693',
   'id_01698',
   'id_01704',
   'id_01716',
   'id_01723',
   'id_01726',
   'id_01730',
   'id_01734',
   'id_01761',
   'id_01762',
   'id_01763',
   'id_01771',
   'id_01782',
   'id_01797',
   'id_01805',
   'id_01806',
   'id_01807',
   'id_01811',
   'id_01812',
   'id_01828',
   'id_01833',
   'id_01835',
   'id_01852',
   'id_01857',
   'id_01869',
   'id_01879',
   'id_01881',
   'id_01883',
   'id_01885',
   'id_01896',
   'id_01903',
   'id_01912',
   'id_01913',
   'id_01928',
   'id_01941',
   'id_01944',
   'id_01949',
   'id_01964',
   'id_01969',
   'id_01988',
   'id_01998',
   'id_02003',
   'id_02018',
   'id_02021',
   'id_02023',
   'id_02029',
   'id_02035',
   'id_02037',
   'id_02046',
   'id_02054',
   'id_02079',
   'id_02100',
   'id_02110',
   'id_02131',
   'id_02135',
   'id_02143',
   'id_02146',
   'id_02154',
   'id_02160',
   'id_02162',
   'id_02168',
   'id_02175',
   'id_02176',
   'id_02180',
   'id_02210',
   'id_02232',
   'id_02234',
   'id_02261',
   'id_02264',
   'id_02265',
   'id_02267',
   'id_02274',
   'id_02275',
   'id_02277',
   'id_02278',
   'id_02288',
   'id_02296',
   'id_02323',
   'id_02339',
   'id_02344',
   'id_02347',
   'id_02363',
   'id_02366',
   'id_02369',
   'id_02374',
   'id_02376',
   'id_02391',
   'id_02395',
   'id_02397',
   'id_02398',
   'id_02406',
   'id_02422',
   'id_02424',
   'id_02439',
   'id_02447',
   'id_02461',
   'id_02465',
   'id_02477',
   'id_02496',
   'id_02497',
   'id_02504',
   'id_02505',
   'id_02510',
   'id_02511',
   'id_02520',
   'id_02540',
   'id_02546',
   'id_02549',
   'id_02568',
   'id_02576',
   'id_02586',
   'id_02591',
   'id_02592',
   'id_02594',
   'id_02596',
   'id_02601',
   'id_02603',
   'id_02618',
   'id_02622',
   'id_02635',
   'id_02641',
   'id_02648',
   'id_02660',
   'id_02674',
   'id_02694',
   'id_02695',
   'id_02699',
   'id_02728',
   'id_02730',
   'id_02732',
   'id_02747',
   'id_02751',
   'id_02757',
   'id_02760',
   'id_02768',
   'id_02800',
   'id_02807',
   'id_02808',
   'id_02809',
   'id_02828',
   'id_02840',
   'id_02858',
   'id_02865',
   'id_02870',
   'id_02879',
   'id_02882',
   'id_02883',
   'id_02906',
   'id_02912',
   'id_02921',
   'id_02926',
   'id_02971',
   'id_02977',
   'id_02980',
   'id_02998',
   'id_03026',
   'id_03030',
   'id_03038',
   'id_03041',
   'id_03045',
   'id_03058',
   'id_03082',
   'id_03086',
   'id_03092',
   'id_03098',
   'id_03111',
   'id_03114',
   'id_03124',
   'id_03134',
   'id_03156',
   'id_03169',
   'id_03182',
   'id_03184',
   'id_03190',
   'id_03201',
   'id_03202',
   'id_03207',
   'id_03230',
   'id_03238',
   'id_03264',
   'id_03266',
   'id_03276',
   'id_03281',
   'id_03284',
   'id_03285',
   'id_03292',
   'id_03296',
   'id_03298',
   'id_03306',
   'id_03325',
   'id_03331',
   'id_03332',
   'id_03341',
   'id_03346',
   'id_03361',
   'id_03372',
   'id_03385',
   'id_03421',
   'id_03422',
   'id_03425',
   'id_03429',
   'id_03434',
   'id_03438',
   'id_03456',
   'id_03463',
   'id_03465',
   'id_03472',
   'id_03474',
   'id_03491',
   'id_03512',
   'id_03518',
   'id_03520',
   'id_03529',
   'id_03539',
   'id_03544',
   'id_03557',
   'id_03568',
   'id_03575',
   'id_03577',
   'id_03609',
   'id_03612',
   'id_03614',
   'id_03619',
   'id_03630',
   'id_03633',
   'id_03636',
   'id_03654',
   'id_03662',
   'id_03667',
   'id_03683',
   'id_03685',
   'id_03687',
   'id_03690',
   'id_03691',
   'id_03720',
   'id_03729',
   'id_03744',
   'id_03749',
   'id_03762',
   'id_03771',
   'id_03784',
   'id_03845',
   'id_03848',
   'id_03849',
   'id_03850',
   'id_03867',
   'id_03879',
   'id_03884',
   'id_03897',
   'id_03909',
   'id_03924',
   'id_03932',
   'id_03941',
   'id_03946',
   'id_03948',
   'id_03969',
   'id_03975',
   'id_03989',
   'id_04009',
   'id_04021',
   'id_04026',
   'id_04028',
   'id_04036',
   'id_04067',
   'id_04069',
   'id_04070',
   'id_04109',
   'id_04125',
   'id_04127',
   'id_04130',
   'id_04132',
   'id_04134',
   'id_04152',
   'id_04188',
   'id_04191',
   'id_04197',
   'id_04198',
   'id_04204',
   'id_04218',
   'id_04220',
   'id_04233',
   'id_04234',
   'id_04247',
   'id_04248',
   'id_04254',
   'id_04257',
   'id_04267',
   'id_04289',
   'id_04295',
   'id_04297',
   'id_04352',
   'id_04356',
   'id_04359',
   'id_04370',
   'id_04381',
   'id_04382',
   'id_04386',
   'id_04402',
   'id_04406',
   'id_04419',
   'id_04466',
   'id_04485',
   'id_04486',
   'id_04490',
   'id_04498',
   'id_04499',
   'id_04502',
   'id_04508',
   'id_04524',
   'id_04529',
   'id_04545',
   'id_04563',
   'id_04564',
   'id_04570',
   'id_04572',
   'id_04579',
   'id_04581',
   'id_04582',
   'id_04586',
   'id_04589',
   'id_04593',
   'id_04597',
   'id_04603',
   'id_04604',
   'id_04606',
   'id_04610',
   'id_04619',
   'id_04621',
   'id_04634',
   'id_04642',
   'id_04650',
   'id_04666',
   'id_04674',
   'id_04696',
   'id_04703',
   'id_04708',
   'id_04709',
   'id_04720',
   'id_04757',
   'id_04774',
   'id_04778',
   'id_04780',
   'id_04787',
   'id_04792',
   'id_04798',
   'id_04800',
   'id_04806',
   'id_04810',
   'id_04815',
   'id_04820',
   'id_04829',
   'id_04839',
   'id_04863',
   'id_04867',
   'id_04880',
   'id_04910',
   'id_04943',
   'id_04944',
   'id_04960',
   'id_04961',
   'id_04972',
   'id_04982',
   'id_04990',
   'id_05006',
   'id_05010',
   'id_05017',
   'id_05018',
   'id_05026',
   'id_05027',
   'id_05043',
   'id_05046',
   'id_05048',
   'id_05062',
   'id_05071',
   'id_05072',
   'id_05074',
   'id_05097',
   'id_05117',
   'id_05130',
   'id_05144',
   'id_05156',
   'id_05167',
   'id_05168',
   'id_05170',
   'id_05171',
   'id_05178',
   'id_05182',
   'id_05193',
   'id_05197',
   'id_05201',
   'id_05208',
   'id_05216',
   'id_05217',
   'id_05223',
   'id_05236',
   'id_05241',
   'id_05257',
   'id_05263',
   'id_05264',
   'id_05271',
   'id_05277',
   'id_05278',
   'id_05293',
   'id_05311',
   'id_05314',
   'id_05323',
   'id_05331',
   'id_05347',
   'id_05349',
   'id_05353',
   'id_05357',
   'id_05360',
   'id_05367',
   'id_05372',
   'id_05374',
   'id_05398',
   'id_05402',
   'id_05404',
   'id_05410',
   'id_05416',
   'id_05425',
   'id_05427',
   'id_05430',
   'id_05436',
   'id_05440',
   'id_05442',
   'id_05461',
   'id_05464',
   'id_05470',
   'id_05504',
   'id_05511',
   'id_05512',
   'id_05516',
   'id_05529',
   'id_05537',
   'id_05541',
   'id_05547',
   'id_05554',
   'id_05610',
   'id_05628',
   'id_05636',
   'id_05642',
   'id_05656',
   'id_05664',
   'id_05665',
   'id_05688',
   'id_05706',
   'id_05716',
   'id_05717',
   'id_05725',
   'id_05727',
   'id_05735',
   'id_05740',
   'id_05742',
   'id_05747',
   'id_05749',
   'id_05759',
   'id_05762',
   'id_05774',
   'id_05776',
   'id_05794',
   'id_05797',
   'id_05809',
   'id_05814',
   'id_05817',
   'id_05922',
   'id_05925',
   'id_05926',
   'id_05936',
   'id_05945',
   'id_05946',
   'id_05951',
   'id_05954',
   'id_05962',
   'id_05970',
   'id_05971',
   'id_06001',
   'id_06004',
   'id_06020',
   'id_06023',
   'id_06036',
   'id_06046',
   'id_06047',
   'id_06053',
   'id_06063',
   'id_06067',
   'id_06076',
   'id_06080',
   'id_06089',
   'id_06092',
   'id_06096',
   'id_06102',
   'id_06120',
   'id_06125',
   'id_06130',
   'id_06136',
   'id_06148',
   'id_06159',
   'id_06170',
   'id_06184',
   'id_06186',
   'id_06200',
   'id_06217',
   'id_06232',
   'id_06242',
   'id_06252',
   'id_06262',
   'id_06280',
   'id_06297',
   'id_06298',
   'id_06316',
   'id_06328',
   'id_06333',
   'id_06346',
   'id_06349',
   'id_06352',
   'id_06353',
   'id_06356',
   'id_06359',
   'id_06402',
   'id_06403',
   'id_06411',
   'id_06422',
   'id_06428',
   'id_06430',
   'id_06431',
   'id_06439',
   'id_06453',
   'id_06462',
   'id_06466',
   'id_06503',
   'id_06507',
   'id_06540',
   'id_06548',
   'id_06557',
   'id_06565',
   'id_06567',
   'id_06568',
   'id_06574',
   'id_06576',
   'id_06578',
   'id_06587',
   'id_06594',
   'id_06625',
   'id_06627',
   'id_06633',
   'id_06648',
   'id_06651',
   'id_06665',
   'id_06676',
   'id_06687',
   'id_06705',
   'id_06710',
   'id_06730',
   'id_06740',
   'id_06744',
   'id_06746',
   'id_06757',
   'id_06758',
   'id_06771',
   'id_06772',
   'id_06777',
   'id_06786',
   'id_06791',
   'id_06794',
   'id_06797',
   'id_06806',
   'id_06821',
   'id_06834',
   'id_06838',
   'id_06850',
   'id_06868',
   'id_06889',
   'id_06906',
   'id_06909',
   'id_06910',
   'id_06914',
   'id_06921',
   'id_06926',
   'id_06938',
   'id_06943',
   'id_06955',
   'id_06956',
   'id_06957',
   'id_06960',
   'id_06962',
   'id_07043',
   'id_07048',
   'id_07058',
   'id_07059',
   'id_07062',
   'id_07064',
   'id_07070',
   'id_07076',
   'id_07082',
   'id_07097',
   'id_07106',
   'id_07112',
   'id_07127',
   'id_07179',
   'id_07196',
   'id_07206',
   'id_07208',
   'id_07214',
   'id_07217',
   'id_07220',
   'id_07242',
   'id_07244',
   'id_07245',
   'id_07247',
   'id_07255',
   'id_07273',
   'id_07275',
   'id_07286',
   'id_07289',
   'id_07291',
   'id_07308',
   'id_07315',
   'id_07317',
   'id_07318',
   'id_07355',
   'id_07359',
   'id_07383',
   'id_07384',
   'id_07385',
   'id_07389',
   'id_07395',
   'id_07399',
   'id_07402',
   'id_07413',
   'id_07417',
   'id_07431',
   'id_07444',
   'id_07454',
   'id_07475',
   'id_07491',
   'id_07499',
   'id_07510',
   'id_07513',
   'id_07531',
   'id_07535',
   'id_07551',
   'id_07552',
   'id_07572',
   'id_07575',
   'id_07597',
   'id_07600',
   'id_07609',
   'id_07611',
   'id_07614',
   'id_07620',
   'id_07624',
   'id_07626',
   'id_07629',
   'id_07636',
   'id_07649',
   'id_07663',
   'id_07671',
   'id_07673',
   'id_07674',
   'id_07681',
   'id_07685',
   'id_07699',
   'id_07707',
   'id_07708',
   'id_07711',
   'id_07719',
   'id_07725',
   'id_07733',
   'id_07736',
   'id_07757',
   'id_07771',
   'id_07822',
   'id_07833',
   'id_07842',
   'id_07845',
   'id_07867',
   'id_07888',
   'id_07895',
   'id_07913',
   'id_07925',
   'id_07932',
   'id_07952',
   'id_07959',
   'id_07967',
   'id_07975',
   'id_07978',
   'id_07992',
   'id_07996',
   'id_08002',
   'id_08003',
   'id_08026',
   'id_08031',
   'id_08034',
   'id_08038',
   'id_08057',
   'id_08067',
   'id_08074',
   'id_08080',
   'id_08089',
   'id_08094',
   'id_08097',
   'id_08101',
   'id_08120',
   'id_08130',
   'id_08134',
   'id_08144',
   'id_08153',
   'id_08162',
   'id_08163',
   'id_08170',
   'id_08177',
   'id_08178',
   'id_08182',
   'id_08198',
   'id_08216',
   'id_08230',
   'id_08236',
   'id_08240',
   'id_08242',
   'id_08252',
   'id_08254',
   'id_08255',
   'id_08271',
   'id_08277',
   'id_08290',
   'id_08318',
   'id_08321',
   'id_08328',
   'id_08333',
   'id_08338',
   'id_08341',
   'id_08368',
   'id_08369',
   'id_08375',
   'id_08383',
   'id_08385',
   'id_08400',
   'id_08404',
   'id_08410',
   ...],
  'solo_en_2026': ['id_36779',
   'id_36780',
   'id_36781',
   'id_36782',
   'id_36783',
   'id_36784',
   'id_36785',
   'id_36786',
   'id_36787',
   'id_36788',
   'id_36789',
   'id_36790',
   'id_36791',
   'id_36792',
   'id_36793',
   'id_36794',
   'id_36795',
   'id_36796',
   'id_36797',
   'id_36798',
   'id_36799',
   'id_36800',
   'id_36801',
   'id_36802',
   'id_36803',
   'id_36804',
   'id_36805',
   'id_36806',
   'id_36807',
   'id_36808',
   'id_36809',
   'id_36810',
   'id_36811',
   'id_36812',
   'id_36813',
   'id_36814',
   'id_36815',
   'id_36816',
   'id_36817',
   'id_36818',
   'id_36819',
   'id_36820',
   'id_36821',
   'id_36822',
   'id_36823',
   'id_36824',
   'id_36825',
   'id_36826',
   'id_36827',
   'id_36828',
   'id_36829',
   'id_36830',
   'id_36831',
   'id_36832',
   'id_36833',
   'id_36834',
   'id_36835',
   'id_36836',
   'id_36837',
   'id_36838',
   'id_36839',
   'id_36840',
   'id_36841',
   'id_36842',
   'id_36843',
   'id_36844',
   'id_36845',
   'id_36846',
   'id_36847',
   'id_36848',
   'id_36849',
   'id_36850',
   'id_36851',
   'id_36852',
   'id_36853',
   'id_36854',
   'id_36855',
   'id_36856',
   'id_36857',
   'id_36858',
   'id_36859',
   'id_36860',
   'id_36861',
   'id_36862',
   'id_36863',
   'id_36864',
   'id_36865',
   'id_36866',
   'id_36867',
   'id_36868',
   'id_36869',
   'id_36870',
   'id_36871',
   'id_36872',
   'id_36873',
   'id_36874',
   'id_36875',
   'id_36876',
   'id_36877',
   'id_36878',
   'id_36879',
   'id_36880',
   'id_36881',
   'id_36882',
   'id_36883',
   'id_36884',
   'id_36885',
   'id_36886',
   'id_36887',
   'id_36888',
   'id_36889',
   'id_36890',
   'id_36891',
   'id_36892',
   'id_36893',
   'id_36894',
   'id_36895',
   'id_36896',
   'id_36897',
   'id_36898',
   'id_36899',
   'id_36900',
   'id_36901',
   'id_36902',
   'id_36903',
   'id_36904',
   'id_36905',
   'id_36906',
   'id_36907',
   'id_36908',
   'id_36909',
   'id_36910',
   'id_36911',
   'id_36912',
   'id_36913',
   'id_36914',
   'id_36915',
   'id_36916',
   'id_36917',
   'id_36918',
   'id_36919',
   'id_36920',
   'id_36921',
   'id_36922',
   'id_36923',
   'id_36924',
   'id_36925',
   'id_36926',
   'id_36927',
   'id_36928',
   'id_36929',
   'id_36930',
   'id_36931',
   'id_36932',
   'id_36933',
   'id_36934',
   'id_36935',
   'id_36936',
   'id_36937',
   'id_36938',
   'id_36939',
   'id_36940',
   'id_36941',
   'id_36942',
   'id_36943',
   'id_36944',
   'id_36945',
   'id_36946',
   'id_36947',
   'id_36948',
   'id_36949',
   'id_36950',
   'id_36951',
   'id_36952',
   'id_36953',
   'id_36954',
   'id_36955',
   'id_36956',
   'id_36957',
   'id_36958',
   'id_36959',
   'id_36960',
   'id_36961',
   'id_36962',
   'id_36963',
   'id_36964',
   'id_36965',
   'id_36966',
   'id_36967',
   'id_36968',
   'id_36969',
   'id_36970',
   'id_36971',
   'id_36972',
   'id_36973',
   'id_36974',
   'id_36975',
   'id_36976',
   'id_36977',
   'id_36978',
   'id_36979',
   'id_36980',
   'id_36981',
   'id_36982',
   'id_36983',
   'id_36984',
   'id_36985',
   'id_36986',
   'id_36987',
   'id_36988',
   'id_36989',
   'id_36990',
   'id_36991',
   'id_36992',
   'id_36993',
   'id_36994',
   'id_36995',
   'id_36996',
   'id_36997',
   'id_36998',
   'id_36999',
   'id_37000',
   'id_37001',
   'id_37002',
   'id_37003',
   'id_37004',
   'id_37005',
   'id_37006',
   'id_37007',
   'id_37008',
   'id_37009',
   'id_37010',
   'id_37011',
   'id_37012',
   'id_37013',
   'id_37014',
   'id_37015',
   'id_37016',
   'id_37017',
   'id_37018',
   'id_37019',
   'id_37020',
   'id_37021',
   'id_37022',
   'id_37023',
   'id_37024',
   'id_37025',
   'id_37026',
   'id_37027',
   'id_37028',
   'id_37029',
   'id_37030',
   'id_37031',
   'id_37032',
   'id_37033',
   'id_37034',
   'id_37035',
   'id_37036',
   'id_37037',
   'id_37038',
   'id_37039',
   'id_37040',
   'id_37041',
   'id_37042',
   'id_37043',
   'id_37044',
   'id_37045',
   'id_37046',
   'id_37047',
   'id_37048',
   'id_37049',
   'id_37050',
   'id_37051',
   'id_37052',
   'id_37053',
   'id_37054',
   'id_37055',
   'id_37056',
   'id_37057',
   'id_37058',
   'id_37059',
   'id_37060',
   'id_37061',
   'id_37062',
   'id_37063',
   'id_37064',
   'id_37065',
   'id_37066',
   'id_37067',
   'id_37068',
   'id_37069',
   'id_37070',
   'id_37071',
   'id_37072',
   'id_37073',
   'id_37074',
   'id_37075',
   'id_37076',
   'id_37077',
   'id_37078',
   'id_37079',
   'id_37080',
   'id_37081',
   'id_37082',
   'id_37083',
   'id_37084',
   'id_37085',
   'id_37086',
   'id_37087',
   'id_37088',
   'id_37089',
   'id_37090',
   'id_37091',
   'id_37092',
   'id_37093',
   'id_37094',
   'id_37095',
   'id_37096',
   'id_37097',
   'id_37098',
   'id_37099',
   'id_37100',
   'id_37101',
   'id_37102',
   'id_37103',
   'id_37104',
   'id_37105',
   'id_37106',
   'id_37107',

In [27]:
# Combinaciones de categorias con cantidades numericas distintas entre anios
resultado["cantidades_desfasadas"].head(20)

,ID_persona,ID_CENTRO_docentes,Sexo,ZONA,tipo_centro,Rubro,dept_nombre,ciclo,grado,grupo,MATERIA,CONTEXTO,tipo,columna,valor_2025,valor_2026,diferencia
0,id_00011,centro_0014,m,urbana,liceo publico,dges,rivera,4to. ciclo,2,2do.csh g. 3,filosofia,NaN,docentes,Dias6,17.0,14.0,3.0
1,id_00011,centro_0014,m,urbana,liceo publico,dges,rivera,4to. ciclo,2,2do.csh g. 5,filosofia,NaN,docentes,Dias6,17.0,14.0,3.0
2,id_00011,centro_0014,m,urbana,liceo publico,dges,rivera,bachillerato,2,2do.hum. g. 1_1osem,filosofia,NaN,docentes,Dias6,17.0,14.0,3.0
3,id_00013,centro_0017,f,urbana,utu,dgetp,montevideo,educacion basica integrada,7,7a||0,matematica,NaN,docentes,Dias6,6.0,2.0,4.0
4,id_00013,centro_0017,f,urbana,utu,dgetp,montevideo,educacion basica integrada,7,7b||0,matematica,NaN,docentes,Dias6,6.0,2.0,4.0
5,id_00013,centro_0017,f,urbana,utu,dgetp,montevideo,educacion basica integrada,8,8a||0,matematica,NaN,docentes,Dias6,6.0,2.0,4.0
6,id_00013,centro_0017,f,urbana,utu,dgetp,montevideo,educacion basica integrada,8,8b||0,matematica,NaN,docentes,Dias6,6.0,2.0,4.0
7,id_00016,centro_0020,m,urbana,liceo publico,dges,montevideo,bachillerato,2,2do.hum. g. 1_1osem,historia,NaN,docentes,Dias6,1.0,0.0,1.0
8,id_00017,centro_0022,m,urbana,liceo publico,dges,canelones,ciclo basico,1,1ro.ee g. 2_anual_s1,informatica e.e.,NaN,docentes,Dias6,21.0,22.0,-1.0
9,id_00017,centro_0022,m,urbana,liceo publico,dges,canelones,ciclo basico,2,2do.ee g. 2_anual_s1,informatica e.e.,NaN,docentes,Dias6,21.0,22.0,-1.0
10,id_00017,centro_0023,m,urbana,utu,dgetp,canelones,educacion basica integrada,9,9a||0,ciencias de computacion - prog.,NaN,docentes,Dias6,21.0,22.0,-1.0
11,id_00024,centro_0030,f,urbana,liceo publico,dges,canelones,3er. ciclo ebi,8,8vo. g. 4,matematica,NaN,docentes,Dias6,7.0,6.0,1.0
12,id_00024,centro_0030,f,urbana,liceo publico,dges,canelones,3er. ciclo ebi,9,9no. g. 5,matematica,NaN,docentes,Dias6,7.0,6.0,1.0
13,id_00024,centro_0031,f,urbana,utu,dgetp,canelones,educacion basica integrada,7,7a||0,matematica,NaN,docentes,Dias6,7.0,6.0,1.0
14,id_00024,centro_0031,f,urbana,utu,dgetp,canelones,educacion basica integrada,7,7b||0,matematica,NaN,docentes,Dias6,7.0,6.0,1.0
15,id_00024,centro_0031,f,urbana,utu,dgetp,canelones,educacion basica integrada,8,8a||0,matematica,NaN,docentes,Dias6,7.0,6.0,1.0
16,id_00024,centro_0031,f,urbana,utu,dgetp,canelones,educacion basica integrada,8,8b||0,matematica,NaN,docentes,Dias6,7.0,6.0,1.0
17,id_00026,centro_0033,m,urbana,liceo publico,dges,montevideo,4to. ciclo,1,1o.ems g. 2,historia,NaN,docentes,Dias6,4.0,8.0,-4.0
18,id_00026,centro_0033,m,urbana,liceo publico,dges,montevideo,4to. ciclo,1,1o.ems g. 3,historia,NaN,docentes,Dias6,4.0,8.0,-4.0
19,id_00029,centro_0037,f,urbana,liceo publico,dges,montevideo,4to. ciclo,3,3ro.cvh g. 1,ingles,NaN,docentes,Dias6,17.0,2.0,15.0

## 3. Duplicados por año

`reporte_duplicados` informa (no modifica); `detectar_duplicados` devuelve la máscara operable.

In [28]:
print(reporte_duplicados(doc25))
print()
print(reporte_duplicados(doc26))

DUPLICADOS
========================================
Filas totales: 148372
Columnas consideradas: todas
Grupos de valores repetidos: 6205
Filas involucradas en duplicados (incluye la primera copia): 12654
Filas 'extra' (sobrarían si se deduplica dejando 1 copia por grupo): 6449
Porcentaje de filas extra sobre el total: 4.3%

DUPLICADOS
========================================
Filas totales: 155745
Columnas consideradas: todas
Grupos de valores repetidos: 553
Filas involucradas en duplicados (incluye la primera copia): 1194
Filas 'extra' (sobrarían si se deduplica dejando 1 copia por grupo): 641
Porcentaje de filas extra sobre el total: 0.4%

In [29]:
# Ejemplo: ver las filas duplicadas de 2025 (sin eliminar nada)
mask_dup_25 = detectar_duplicados(doc25, keep=False)
doc25[mask_dup_25].head(20)

,ID_persona,ID_CENTRO_docentes,Dias6,Dias5,Dias4,Sexo,ZONA,tipo_centro,Rubro,dept_nombre,...,IVSMEDIA,ANIOLECTIVO,ivsmedia_q,contexto_q,contexto_zona,vuln_q,dias_totales,accedio,tipo,anio
16,ID_00005,CENTRO_0006,13,16,13,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,5.0,Urbano,5.0,42,1,docentes,2025
17,ID_00005,CENTRO_0006,13,16,13,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,5.0,Urbano,5.0,42,1,docentes,2025
18,ID_00006,CENTRO_0007,14,18,11,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,1.0,Urbano,1.0,43,1,docentes,2025
19,ID_00006,CENTRO_0007,14,18,11,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,1.0,Urbano,1.0,43,1,docentes,2025
74,ID_00020,CENTRO_0025,3,9,14,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,4.0,Urbano,4.0,26,1,docentes,2025
75,ID_00020,CENTRO_0025,3,9,14,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,4.0,Urbano,4.0,26,1,docentes,2025
85,ID_00023,CENTRO_0029,2,10,5,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,4.0,Urbano,4.0,17,1,docentes,2025
86,ID_00023,CENTRO_0029,2,10,5,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,4.0,Urbano,4.0,17,1,docentes,2025
149,ID_00038,CENTRO_0049,8,15,6,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,29,1,docentes,2025
150,ID_00038,CENTRO_0049,8,15,6,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,29,1,docentes,2025
151,ID_00038,CENTRO_0050,8,15,6,F,Urbana,Utu,DGETP,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,29,1,docentes,2025
152,ID_00038,CENTRO_0050,8,15,6,F,Urbana,Utu,DGETP,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,29,1,docentes,2025
175,ID_00043,CENTRO_0001,12,7,6,M,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,25,1,docentes,2025
176,ID_00043,CENTRO_0001,12,7,6,M,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,25,1,docentes,2025
274,ID_00062,CENTRO_0085,2,0,1,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,3,1,docentes,2025
275,ID_00062,CENTRO_0085,2,0,1,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,3,1,docentes,2025
277,ID_00064,CENTRO_0040,3,5,7,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,5.0,Urbano,5.0,15,1,docentes,2025
278,ID_00064,CENTRO_0040,3,5,7,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,5.0,Urbano,5.0,15,1,docentes,2025
279,ID_00065,CENTRO_0087,3,0,7,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,2.0,Urbano,2.0,10,1,docentes,2025
280,ID_00065,CENTRO_0087,3,0,7,F,Urbana,Escuela Pública,DGEIP,MONTEVIDEO,...,NaN,2025,NaN,2.0,Urbano,2.0,10,1,docentes,2025

## 4. Detección y limpieza (centralizadas en el módulo)

`compare_datasets_generic.py` completa el patrón *reporte → detección → limpieza* para cada tema. El notebook solo **importa** y usa:

| Tema | Reporte | Detección (operable) | Limpieza → DataFrame nuevo |
|---|---|---|---|
| Comparación | `reporte_comparacion` / `compare_datasets` | `detectar_desfasajes` | — |
| Duplicados | `reporte_duplicados` | `detectar_duplicados` | `limpiar_duplicados_df` |

### 4a. Comparación → detección operable

`detectar_desfasajes` deriva de `compare_datasets` (que solo reporta) y devuelve tablas listas para filtrar/contar, igual que `detectar_duplicados` devuelve una máscara. Con `con_filas=True` retorna además la columna `n_filas`.

In [30]:
# Detección operable (tabla) a partir del reporte de comparación
desfasajes = detectar_desfasajes(doc25c, doc26c, name1="2025", name2="2026")

print("Categorias desfasadas (filas):", desfasajes["categorias"].shape[0])
print("Cantidades desfasadas (filas):", desfasajes["cantidades"].shape[0])

# Cuántos valores desfasados hay por columna y en qué año aparecen
resumen_cat = (desfasajes["categorias"]
               .groupby(["columna", "solo_en"]).size()
               .unstack(fill_value=0))
resumen_cat

Categorias desfasadas (filas): 12971
Cantidades desfasadas (filas): 160817

solo_en             2025  2026
columna
ID_CENTRO_docentes    55   136
ID_persona          5337  6916
MATERIA              126   185
ciclo                  2     2
grado                  0     1
grupo                109   102

### 4b. Duplicados → limpieza que devuelve un DataFrame nuevo

`detectar_duplicados` devuelve la máscara operable; `limpiar_duplicados_df` (del módulo) la aplica y retorna un **DataFrame nuevo** sin las filas duplicadas, sin modificar el original. Se aplica a cada año y se guarda como `docentes_<anio>_dedup.csv`.

In [31]:
print("Docentes 2025:")
doc25_sin_dups = limpiar_duplicados_df(doc25, verbose=True)
print("Docentes 2026:")
doc26_sin_dups = limpiar_duplicados_df(doc26, verbose=True)
doc25_sin_dups.head()

Docentes 2025:
  6449 filas duplicadas eliminadas: 148372 -> 141923
Docentes 2026:
  641 filas duplicadas eliminadas: 155745 -> 155104

,ID_persona,ID_CENTRO_docentes,Dias6,Dias5,Dias4,Sexo,ZONA,tipo_centro,Rubro,dept_nombre,...,IVSMEDIA,ANIOLECTIVO,ivsmedia_q,contexto_q,contexto_zona,vuln_q,dias_totales,accedio,tipo,anio
0,ID_00001,CENTRO_0001,14,14,12,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,40,1,docentes,2025
1,ID_00001,CENTRO_0002,14,14,12,F,Urbana,Liceo Público,DGES,MONTEVIDEO,...,NaN,2025,NaN,NaN,NaN,NaN,40,1,docentes,2025
2,ID_00002,CENTRO_0003,1,0,0,M,Urbana,Liceo Público,DGES,CANELONES,...,NaN,2025,NaN,NaN,NaN,NaN,1,1,docentes,2025
3,ID_00003,CENTRO_0004,2,6,11,F,Urbana,Liceo Público,DGES,SORIANO,...,NaN,2025,NaN,NaN,NaN,NaN,19,1,docentes,2025
4,ID_00003,CENTRO_0004,2,6,11,F,Urbana,Liceo Público,DGES,SORIANO,...,NaN,2025,NaN,NaN,NaN,NaN,19,1,docentes,2025

In [32]:
# Guarda los DataFrames nuevos (sin duplicados) junto a los otros procesados
SALIDA = CARPETA_DATOS / "processed"
doc25_sin_dups.to_csv(SALIDA / "docentes_2025_dedup.csv", index=False)
doc26_sin_dups.to_csv(SALIDA / "docentes_2026_dedup.csv", index=False)
print("Guardados:")
print("  ", (SALIDA / "docentes_2025_dedup.csv").name, doc25_sin_dups.shape)
print("  ", (SALIDA / "docentes_2026_dedup.csv").name, doc26_sin_dups.shape)

Guardados:
   docentes_2025_dedup.csv (141923, 25)
   docentes_2026_dedup.csv (155104, 25)

## 5. Desfasajes después de limpiar duplicados (con porcentaje)

Repetimos la detección de desfasajes, pero ahora sobre `doc25_sin_dups` / `doc26_sin_dups` (ya sin filas duplicadas), y agregamos el **porcentaje** de valores desfasados por columna y el porcentaje de combinaciones con cantidad desfasada.

In [33]:
# Preparar dtypes sobre los datasets ya deduplicados y detectar desfasajes.
# con_filas=True -> la tabla de categorias ya trae n_filas; el dict trae ademas
# 'cantidades' y 'resumen', asi que compare_datasets se ejecuta UNA sola vez.
doc25_sin_dups_c, doc26_sin_dups_c = preparar_para_comparar(doc25_sin_dups, doc26_sin_dups)

desfasajes_dedup = detectar_desfasajes(
    doc25_sin_dups_c, doc26_sin_dups_c, name1="2025", name2="2026", con_filas=True
)
desfasajes_dedup["resumen"]

Columnas vacias en un dataset (excluidas): ['IVSMEDIA', 'ivsmedia_q', 'contexto_zona']
Columnas mixto (num/texto) pasadas a texto: (ninguna)

{'columnas_solo_en_2025': [],
 'columnas_solo_en_2026': [],
 'columnas_categoricas_comparadas': ['ID_persona',
  'ID_CENTRO_docentes',
  'Sexo',
  'ZONA',
  'tipo_centro',
  'Rubro',
  'dept_nombre',
  'ciclo',
  'grado',
  'grupo',
  'MATERIA',
  'CONTEXTO',
  'tipo'],
 'columnas_numericas_comparadas': ['Dias6',
  'Dias5',
  'Dias4',
  'ANIOLECTIVO',
  'contexto_q',
  'vuln_q',
  'dias_totales',
  'accedio',
  'anio'],
 'columnas_con_categorias_desfasadas': ['ID_persona',
  'ID_CENTRO_docentes',
  'ciclo',
  'grado',
  'grupo',
  'MATERIA'],
 'combinaciones_comunes_comparadas': 25907,
 'combinaciones_con_cantidad_desfasada': 158483,
 'filas_totales_2025': 141923,
 'filas_totales_2026': 155104}

In [34]:
# La deteccion ya viene con n_filas (con_filas=True); solo extraemos la tabla.
desfasajes_df = desfasajes_dedup["categorias"]

print("Filas del df de desfasajes:", len(desfasajes_df))
desfasajes_df.head(20)

Filas del df de desfasajes: 12971

               columna        valor solo_en  n_filas
0   ID_CENTRO_docentes  centro_2513    2026      144
1   ID_CENTRO_docentes  centro_2511    2026      129
2   ID_CENTRO_docentes  centro_0366    2025       79
3   ID_CENTRO_docentes  centro_2510    2026       77
4   ID_CENTRO_docentes  centro_2512    2026       70
5   ID_CENTRO_docentes  centro_2514    2026       67
6   ID_CENTRO_docentes  centro_2556    2026       51
7   ID_CENTRO_docentes  centro_2524    2026       47
8   ID_CENTRO_docentes  centro_2536    2026       42
9   ID_CENTRO_docentes  centro_2535    2026       36
10  ID_CENTRO_docentes  centro_2518    2026       34
11  ID_CENTRO_docentes  centro_0936    2025       23
12  ID_CENTRO_docentes  centro_2521    2026       23
13  ID_CENTRO_docentes  centro_2517    2026       21
14  ID_CENTRO_docentes  centro_2519    2026       21
15  ID_CENTRO_docentes  centro_0233    2025       20
16  ID_CENTRO_docentes  centro_0588    2025       20
17  ID_CENTRO_docentes  centro_0884    2025       20
18  ID_CENTRO_docentes  centro_1350    2025       20
19  ID_CENTRO_docentes  centro_2509    2026       18

In [35]:
# % de categorias desfasadas por columna, en DOS bases:
#   - %_valores : sobre el total de valores unicos (union 2025+2026) de la columna
#   - %_filas   : sobre el total de filas (2025 + 2026 deduplicados)
filas_2025 = len(doc25_sin_dups_c)
filas_2026 = len(doc26_sin_dups_c)
total_filas = filas_2025 + filas_2026

filas_pct = []
for col in desfasajes_df["columna"].unique():
    sub = desfasajes_df[desfasajes_df["columna"] == col]
    total_unicos = len(
        set(doc25_sin_dups_c[col].dropna().unique()) | set(doc26_sin_dups_c[col].dropna().unique())
    )
    n_valores = len(sub)
    n_filas_desf = int(sub["n_filas"].sum())
    filas_pct.append({
        "columna": col,
        "valores_desfasados": n_valores,
        "valores_unicos_totales": total_unicos,
        "%_valores": round(100 * n_valores / total_unicos, 2) if total_unicos else 0.0,
        "filas_desfasadas": n_filas_desf,
        "filas_totales": total_filas,
        "%_filas": round(100 * n_filas_desf / total_filas, 2),
    })
pct_categorias = pd.DataFrame(filas_pct).sort_values("%_filas", ascending=False)
pct_categorias

,columna,valores_desfasados,valores_unicos_totales,%_valores,filas_desfasadas,filas_totales,%_filas
2,MATERIA,311,1124,27.67,28600,297027,9.63
1,ID_persona,12253,43694,28.04,26709,297027,8.99
5,grupo,211,664,31.78,23466,297027,7.90
3,ciclo,4,25,16.00,1971,297027,0.66
0,ID_CENTRO_docentes,191,2644,7.22,1718,297027,0.58
4,grado,1,15,6.67,800,297027,0.27

In [36]:
# % de combinaciones con AL MENOS una cantidad desfasada, sobre las combinaciones comunes.
# Ojo: 'cantidades' trae una fila POR CADA columna numerica desfasada
# (una misma combinacion puede aparecer varias veces, una por Dias4/Dias5/...),
# asi que contamos combinaciones UNICAS, no el total de filas.
resumen = desfasajes_dedup["resumen"]
key_cols = resumen["columnas_categoricas_comparadas"]
combinaciones_unicas_desfasadas = desfasajes_dedup["cantidades"][key_cols].drop_duplicates().shape[0]

comunes = resumen["combinaciones_comunes_comparadas"]
pct_cantidades = round(100 * combinaciones_unicas_desfasadas / comunes, 2) if comunes else 0.0

print(f"Combinaciones comunes comparadas:                  {comunes}")
print(f"Filas de cantidad desfasada (1 por columna numerica): {resumen['combinaciones_con_cantidad_desfasada']}")
print(f"Combinaciones UNICAS con al menos 1 cantidad desfasada: {combinaciones_unicas_desfasadas}")
print(f"% de combinaciones con cantidad desfasada: {pct_cantidades}%")

Combinaciones comunes comparadas:                  25907
Filas de cantidad desfasada (1 por columna numerica): 158483
Combinaciones UNICAS con al menos 1 cantidad desfasada: 25907
% de combinaciones con cantidad desfasada: 100.0%

In [37]:
# Top valores desfasados por cantidad de filas, para CADA columna desfasada
# (mismo desglose que se veia para ID_CENTRO_docentes, ahora por columna).
TOP = 15
for col in sorted(desfasajes_df["columna"].unique()):
    sub = desfasajes_df[desfasajes_df["columna"] == col]
    print(f"\n=== {col} — {len(sub)} valores desfasados, {int(sub['n_filas'].sum())} filas ===")
    display(sub.head(TOP).reset_index(drop=True))

print(doc25_sin_dups_c['grado'].unique())

=== ID_CENTRO_docentes — 191 valores desfasados, 1718 filas ===

               columna        valor solo_en  n_filas
0   ID_CENTRO_docentes  centro_2513    2026      144
1   ID_CENTRO_docentes  centro_2511    2026      129
2   ID_CENTRO_docentes  centro_0366    2025       79
3   ID_CENTRO_docentes  centro_2510    2026       77
4   ID_CENTRO_docentes  centro_2512    2026       70
5   ID_CENTRO_docentes  centro_2514    2026       67
6   ID_CENTRO_docentes  centro_2556    2026       51
7   ID_CENTRO_docentes  centro_2524    2026       47
8   ID_CENTRO_docentes  centro_2536    2026       42
9   ID_CENTRO_docentes  centro_2535    2026       36
10  ID_CENTRO_docentes  centro_2518    2026       34
11  ID_CENTRO_docentes  centro_0936    2025       23
12  ID_CENTRO_docentes  centro_2521    2026       23
13  ID_CENTRO_docentes  centro_2517    2026       21
14  ID_CENTRO_docentes  centro_2519    2026       21

=== ID_persona — 12253 valores desfasados, 26709 filas ===

       columna     valor solo_en  n_filas
0   ID_persona  id_40792    2026       21
1   ID_persona  id_42647    2026       21
2   ID_persona  id_42824    2026       19
3   ID_persona  id_37162    2026       17
4   ID_persona  id_41449    2026       17
5   ID_persona  id_35308    2025       16
6   ID_persona  id_38048    2026       16
7   ID_persona  id_32440    2025       15
8   ID_persona  id_37550    2026       15
9   ID_persona  id_05436    2025       14
10  ID_persona  id_10965    2025       14
11  ID_persona  id_26642    2025       14
12  ID_persona  id_27113    2025       14
13  ID_persona  id_28113    2025       14
14  ID_persona  id_33594    2025       14

=== MATERIA — 311 valores desfasados, 28600 filas ===

    columna                           valor solo_en  n_filas
0   MATERIA             educacion ciudadana    2026     2817
1   MATERIA              cs.fisico-quimicas    2026     2740
2   MATERIA                 taller ciencias    2025     2626
3   MATERIA        taller arte - ed.musical    2025     1325
4   MATERIA    taller participacion juvenil    2025     1300
5   MATERIA            historia del uruguay    2025     1284
6   MATERIA                educacion fisica    2026     1256
7   MATERIA      taller expresion artistica    2025     1244
8   MATERIA  cs.computacionales (alf. dig.)    2025     1235
9   MATERIA        taller arte - com.visual    2025     1227
10  MATERIA      conciencia corporal y arte    2025     1184
11  MATERIA  cs.computacionales (tecnolog.)    2025     1182
12  MATERIA   cs.computacionales (program.)    2025     1134
13  MATERIA                      astronomia    2026     1116
14  MATERIA             lengua y literatura    2025     1077

=== ciclo — 4 valores desfasados, 1971 filas ===

  columna                                valor solo_en  n_filas
0   ciclo  articulacion educacion media basica    2025     1526
1   ciclo   educacion media basica tecnologica    2026      414
2   ciclo                  ctt especializacion    2026       22
3   ciclo             bachillerato profesional    2025        9

=== grado — 1 valores desfasados, 800 filas ===

  columna      valor solo_en  n_filas
0   grado  no aplica    2026      800

=== grupo — 211 valores desfasados, 23466 filas ===

   columna                 valor solo_en  n_filas
0    grupo           2do.cv g. 1    2026     1689
1    grupo          3ro.hcp g. 1    2026     1640
2    grupo         3ro.cshd g. 1    2025     1628
3    grupo  sin grupo a cargo||0    2026     1608
4    grupo          3ro.ctq g. 1    2025      912
5    grupo           3ro.ct g. 1    2026      902
6    grupo           2do.cv g. 2    2026      900
7    grupo          3ro.hcp g. 2    2026      856
8    grupo         3ro.cshd g. 2    2025      757
9    grupo                ra1||1    2025      681
10   grupo          3ro.hce g. 1    2026      656
11   grupo         3ro.cshm g. 1    2025      643
12   grupo                 fa||0    2026      610
13   grupo           2do.cv g. 3    2026      514
14   grupo          3ro.hcp g. 3    2026      466

<ArrowStringArray>
[               '1',                '2',                '3',
                '7',                '8',               '4º',
                '9',               '3º',               '2º',
               '6º',               '1º',               '5º',
                '0', 'Seminario Praxis']
Length: 14, dtype: str

In [38]:
# DataFrame de desfasajes de categorias (solo se muestra, no se guarda)
print("desfasajes_df:", desfasajes_df.shape)
desfasajes_df.head(20)

desfasajes_df: (12971, 4)

               columna        valor solo_en  n_filas
0   ID_CENTRO_docentes  centro_2513    2026      144
1   ID_CENTRO_docentes  centro_2511    2026      129
2   ID_CENTRO_docentes  centro_0366    2025       79
3   ID_CENTRO_docentes  centro_2510    2026       77
4   ID_CENTRO_docentes  centro_2512    2026       70
5   ID_CENTRO_docentes  centro_2514    2026       67
6   ID_CENTRO_docentes  centro_2556    2026       51
7   ID_CENTRO_docentes  centro_2524    2026       47
8   ID_CENTRO_docentes  centro_2536    2026       42
9   ID_CENTRO_docentes  centro_2535    2026       36
10  ID_CENTRO_docentes  centro_2518    2026       34
11  ID_CENTRO_docentes  centro_0936    2025       23
12  ID_CENTRO_docentes  centro_2521    2026       23
13  ID_CENTRO_docentes  centro_2517    2026       21
14  ID_CENTRO_docentes  centro_2519    2026       21
15  ID_CENTRO_docentes  centro_0233    2025       20
16  ID_CENTRO_docentes  centro_0588    2025       20
17  ID_CENTRO_docentes  centro_0884    2025       20
18  ID_CENTRO_docentes  centro_1350    2025       20
19  ID_CENTRO_docentes  centro_2509    2026       18